<?php return array (
  'ADMIN_PAGINATION_LIMIT' => '1',
  'GOOGLE_RECAPTCHA_KEY' => '6Ld2SMkbAAAAAOE2ZVMoXXrtPV4GGqSBOQHtjMd1',
  'GOOGLE_RECAPTCHA_SECRET' => '6Ld2SMkbAAAAAEltV0Bfkl3QbL-NC_gJg07JXeFK',
  'PASSWORD_ERROR' => 'Your password must be more than 8 characters long, should contain at-least 1
    Uppercase, 1 Lowercase, 1 Numeric and 1 special character.',
  'PASSWORD_VALIDATION' =>
  array (
    0 => 'required',
    1 => 'min:8',
    2 => 'max:20',
    3 => 'regex:/^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[@#$%^&*!])[A-Za-z\\d@#$%^&*!]{8,}$/',
  ),
  'ZERO_ZERO' => ' 00:00:00',
  'FULL_FULL' => ' 23:59:59',
  'STANDOUT_FOLDER' => '/uploads/standout/',
  'COUPON_FOLDER' => '/uploads/coupons/',
  'COMMENT_FOLDER' => '/uploads/comment/',
  'USER_FOLDER' => '/uploads/user/',
  'LOGO_FOLDER' => '/uploads/logo/',
  'AUDIO_FOLDER' => '/uploads/audio/',
  'POST_FOLDER' => '/uploads/post/',
  'MASTER_DROPDOWN_FOLDER' => '/uploads/master_dropdown/',
  'TYPE_FOLDER' => '/uploads/type/',
  'DROPDOWN_FOLDER' => '/uploads/dropdown/',
  'ADMIN_PROFILE_FOLDER' => '/uploads/admin/',
  'REQUIRED_MIN_2_MAX_30' => 'required|max:30|min:2',
  'REQUIRED_MIN_2_MAX_60' => 'required|max:60|min:2',
  'REQUIRED_NUMERIC' => 'required|numeric',
  'IMAGE_GENERIC_VALIDATION' => 'nullable|image|mimes:jpeg,jpg,png,gif|max:1024',
  'validImageExtensions' => 'jpeg|png|JPEG|PNG|JPG|jpg|gif',
  'maxImageSizeJs' => 1,
  'ADMIN_LISTING_DATE_FORMAT' => 'Y-m-d h:i:s A',
  'FAQ_FOLDER' => '/uploads/faq/',
  'TESTIMONIALS_FOLDER' => '/uploads/testimonials/',
  'GALLERY_FOLDER' => '/uploads/gallery/',
  'META_FOLDER'=> '/uploads/meta/',
  'IMAGE_FOLDER'=> '/uploads/images/',
  'MEDIA_FOLDER'=> '/uploads/media/',
  'BANNER_FOLDER' => '/uploads/banner/',
  'SETTING_DATE_FORMAT_lIST' => array(''=>'Select Date Format','d-M-Y h:i:s A'=>'dd-mm-yyyy h:i:s A','M-d-Y h:i:s A'=>'mm-dd-yyyy h:i:s A','Y-M-d h:i:s A'=>'yyyy-mm-dd h:i:s A', 'd/M/Y h:i:s A' => 'dd/mm/yyyy h:i:s A'),
  'UPLOAD_SERVER_TYPE' => array(''=>'Select Upload Server','Local'=>'Local','Aws'=>'Aws'),
  'IS_MAINTENANCE_MODE' => array(''=>'Select Maintenance Mode','Up'=>'Up','Down'=>'Down'),
  'Zip_Module_List'=> array('User'=>'User Manager','Video'=>'Video Manager','Video'=>'Video Manager','Audio'=>'Audio Manager','Testimonial'=>'Testimonial Manager','Transaction'=>'Transaction Manager','CMS'=>'CMS Manager','EmailTemplate'=>'EmailTemplate Manager','Setting'=>'Setting Manager'),
  'TICKET_STATUS' => array(''=>'Select Ticket Status','0'=>'New','1'=>'Progress','2'=>'Closed'),
);
