<?php
 $data = [
    [
        'name' => 'Andorra',
        'emoji' => '🇦🇩',
        'dial_code' => '+376',
        'image' => 'AD.svg',
        'status' => 1,
    ],
    [
        'name' => 'United Arab Emirates',
        'emoji' => '🇦🇪',
        'dial_code' => '+971',
        'image' => 'AE.svg',
        'status' => 1,
    ],
    [
        'name' => 'Afghanistan',
        'emoji' => '🇦🇫',
        'dial_code' => '+93',
        'image' => 'AF.svg',
        'status' => 1,
    ],
    [
        'name' => 'Antigua & Barbuda',
        'emoji' => '🇦🇬',
        'dial_code' => '+1268',
        'image' => 'AG.svg',
        'status' => 1,
    ],
    [
        'name' => 'Anguilla',
        'emoji' => '🇦🇮',
        'dial_code' => '+1264',
        'image' => 'AI.svg',
        'status' => 1,
    ],
    [
        'name' => 'Albania',
        'emoji' => '🇦🇱',
        'dial_code' => '+355',
        'image' => 'AL.svg',
        'status' => 1,
    ],
    [
        'name' => 'Armenia',
        'emoji' => '🇦🇲',
        'dial_code' => '+374',
        'image' => 'AM.svg',
        'status' => 1,
    ],
    [
        'name' => 'Angola',
        'emoji' => '🇦🇴',
        'dial_code' => '+244',
        'image' => 'AO.svg',
        'status' => 1,
    ],
    [
        'name' => 'Antarctica',
        'emoji' => '🇦🇶',
        'dial_code' => '+672',
        'image' => 'AQ.svg',
        'status' => 1,
    ],
    [
        'name' => 'Argentina',
        'emoji' => '🇦🇷',
        'dial_code' => '+54',
        'image' => 'AR.svg',
        'status' => 1,
    ],
    [
        'name' => 'American Samoa',
        'emoji' => '🇦🇸',
        'dial_code' => '+1684',
        'image' => 'AS.svg',
        'status' => 1,
    ],
    [
        'name' => 'Austria',
        'emoji' => '🇦🇹',
        'dial_code' => '+43',
        'image' => 'AT.svg',
        'status' => 1,
    ],
    [
        'name' => 'Australia',
        'emoji' => '🇦🇺',
        'dial_code' => '+61',
        'image' => 'AU.svg',
        'status' => 1,
    ],
    [
        'name' => 'Aruba',
        'emoji' => '🇦🇼',
        'dial_code' => '+297',
        'image' => 'AW.svg',
        'status' => 1,
    ],
    [
        'name' => '0',
        'emoji' => '🇦🇽',
        'dial_code' => '+358',
        'image' => 'AX.svg',
        'status' => 1,
    ],
    [
        'name' => 'Azerbaijan',
        'emoji' => '🇦🇿',
        'dial_code' => '+994',
        'image' => 'AZ.svg',
        'status' => 1,
    ],
    [
        'name' => 'Bosnia & Herzegovina',
        'emoji' => '🇧🇦',
        'dial_code' => '+387',
        'image' => 'BA.svg',
        'status' => 1,
    ],
    [
        'name' => 'Barbados',
        'emoji' => '🇧🇧',
        'dial_code' => '+1246',
        'image' => 'BB.svg',
        'status' => 1,
    ],
    [
        'name' => 'Bangladesh',
        'emoji' => '🇧🇩',
        'dial_code' => '+880',
        'image' => 'BD.svg',
        'status' => 1,
    ],
    [
        'name' => 'Belgium',
        'emoji' => '🇧🇪',
        'dial_code' => '+32',
        'image' => 'BE.svg',
        'status' => 1,
    ],
    [
        'name' => 'Burkina Faso',
        'emoji' => '🇧🇫',
        'dial_code' => '+226',
        'image' => 'BF.svg',
        'status' => 1,
    ],
    [
        'name' => 'Bulgaria',
        'emoji' => '🇧🇬',
        'dial_code' => '+359',
        'image' => 'BG.svg',
        'status' => 1,
    ],
    [
        'name' => 'Bahrain',
        'emoji' => '🇧🇭',
        'dial_code' => '+973',
        'image' => 'BH.svg',
        'status' => 1,
    ],
    [
        'name' => 'Burundi',
        'emoji' => '🇧🇮',
        'dial_code' => '+257',
        'image' => 'BI.svg',
        'status' => 1,
    ],
    [
        'name' => 'Benin',
        'emoji' => '🇧🇯',
        'dial_code' => '+229',
        'image' => 'BJ.svg',
        'status' => 1,
    ],
    [
        'name' => 'St. Barth',
        'emoji' => '🇧🇱',
        'dial_code' => '+590',
        'image' => 'BL.svg',
        'status' => 1,
    ],
    [
        'name' => 'Bermuda',
        'emoji' => '🇧🇲',
        'dial_code' => '+1441',
        'image' => 'BM.svg',
        'status' => 1,
    ],
    [
        'name' => 'Brunei',
        'emoji' => '🇧🇳',
        'dial_code' => '+673',
        'image' => 'BN.svg',
        'status' => 1,
    ],
    [
        'name' => 'Bolivia',
        'emoji' => '🇧🇴',
        'dial_code' => '+591',
        'image' => 'BO.svg',
        'status' => 1,
    ],
    [
        'name' => 'Brazil',
        'emoji' => '🇧🇷',
        'dial_code' => '+55',
        'image' => 'BR.svg',
        'status' => 1,
    ],
    [
        'name' => 'Bahamas',
        'emoji' => '🇧🇸',
        'dial_code' => '+1242',
        'image' => 'BS.svg',
        'status' => 1,
    ],
    [
        'name' => 'Bhutan',
        'emoji' => '🇧🇹',
        'dial_code' => '+975',
        'image' => 'BT.svg',
        'status' => 1,
    ],
    [
        'name' => 'Botswana',
        'emoji' => '🇧🇼',
        'dial_code' => '+267',
        'image' => 'BW.svg',
        'status' => 1,
    ],
    [
        'name' => 'Belarus',
        'emoji' => '🇧🇾',
        'dial_code' => '+375',
        'image' => 'BY.svg',
        'status' => 1,
    ],
    [
        'name' => 'Belize',
        'emoji' => '🇧🇿',
        'dial_code' => '+501',
        'image' => 'BZ.svg',
        'status' => 1,
    ],
    [
        'name' => 'Canada',
        'emoji' => '🇨🇦',
        'dial_code' => '+1',
        'image' => 'CA.svg',
        'status' => 1,
    ],
    [
        'name' => 'Cocos (Keeling) Islands',
        'emoji' => '🇨🇨',
        'dial_code' => '+61',
        'image' => 'CC.svg',
        'status' => 1,
    ],
    [
        'name' => 'Congo - Kinshasa',
        'emoji' => '🇨🇩',
        'dial_code' => '+243',
        'image' => 'CD.svg',
        'status' => 1,
    ],
    [
        'name' => 'Central African Republic',
        'emoji' => '🇨🇫',
        'dial_code' => '+236',
        'image' => 'CF.svg',
        'status' => 1,
    ],
    [
        'name' => 'Congo - Brazzaville',
        'emoji' => '🇨🇬',
        'dial_code' => '+242',
        'image' => 'CG.svg',
        'status' => 1,
    ],
    [
        'name' => 'Switzerland',
        'emoji' => '🇨🇭',
        'dial_code' => '+41',
        'image' => 'CH.svg',
        'status' => 1,
    ],
    [
        'name' => 'C',
        'emoji' => '🇨🇮',
        'dial_code' => '+225',
        'image' => 'CI.svg',
        'status' => 1,
    ],
    [
        'name' => 'Cook Islands',
        'emoji' => '🇨🇰',
        'dial_code' => '+682',
        'image' => 'CK.svg',
        'status' => 1,
    ],
    [
        'name' => 'Chile',
        'emoji' => '🇨🇱',
        'dial_code' => '+56',
        'image' => 'CL.svg',
        'status' => 1,
    ],
    [
        'name' => 'Cameroon',
        'emoji' => '🇨🇲',
        'dial_code' => '+237',
        'image' => 'CM.svg',
        'status' => 1,
    ],
    [
        'name' => 'China',
        'emoji' => '🇨🇳',
        'dial_code' => '+86',
        'image' => 'CN.svg',
        'status' => 1,
    ],
    [
        'name' => 'Colombia',
        'emoji' => '🇨🇴',
        'dial_code' => '+57',
        'image' => 'CO.svg',
        'status' => 1,
    ],
    [
        'name' => 'Costa Rica',
        'emoji' => '🇨🇷',
        'dial_code' => '+506',
        'image' => 'CR.svg',
        'status' => 1,
    ],
    [
        'name' => 'Cuba',
        'emoji' => '🇨🇺',
        'dial_code' => '+53',
        'image' => 'CU.svg',
        'status' => 1,
    ],
    [
        'name' => 'Cape Verde',
        'emoji' => '🇨🇻',
        'dial_code' => '+238',
        'image' => 'CV.svg',
        'status' => 1,
    ],
    [
        'name' => 'Christmas Island',
        'emoji' => '🇨🇽',
        'dial_code' => '+61',
        'image' => 'CX.svg',
        'status' => 1,
    ],
    [
        'name' => 'Cyprus',
        'emoji' => '🇨🇾',
        'dial_code' => '+357',
        'image' => 'CY.svg',
        'status' => 1,
    ],
    [
        'name' => 'Czechia',
        'emoji' => '🇨🇿',
        'dial_code' => '+420',
        'image' => 'CZ.svg',
        'status' => 1,
    ],
    [
        'name' => 'Germany',
        'emoji' => '🇩🇪',
        'dial_code' => '+49',
        'image' => 'DE.svg',
        'status' => 1,
    ],
    [
        'name' => 'Djibouti',
        'emoji' => '🇩🇯',
        'dial_code' => '+253',
        'image' => 'DJ.svg',
        'status' => 1,
    ],
    [
        'name' => 'Denmark',
        'emoji' => '🇩🇰',
        'dial_code' => '+45',
        'image' => 'DK.svg',
        'status' => 1,
    ],
    [
        'name' => 'Dominica',
        'emoji' => '🇩🇲',
        'dial_code' => '+1767',
        'image' => 'DM.svg',
        'status' => 1,
    ],
    [
        'name' => 'Dominican Republic',
        'emoji' => '🇩🇴',
        'dial_code' => '+1849',
        'image' => 'DO.svg',
        'status' => 1,
    ],
    [
        'name' => 'Algeria',
        'emoji' => '🇩🇿',
        'dial_code' => '+213',
        'image' => 'DZ.svg',
        'status' => 1,
    ],
    [
        'name' => 'Ecuador',
        'emoji' => '🇪🇨',
        'dial_code' => '+593',
        'image' => 'EC.svg',
        'status' => 1,
    ],
    [
        'name' => 'Estonia',
        'emoji' => '🇪🇪',
        'dial_code' => '+372',
        'image' => 'EE.svg',
        'status' => 1,
    ],
    [
        'name' => 'Egypt',
        'emoji' => '🇪🇬',
        'dial_code' => '+20',
        'image' => 'EG.svg',
        'status' => 1,
    ],
    [
        'name' => 'Eritrea',
        'emoji' => '🇪🇷',
        'dial_code' => '+291',
        'image' => 'ER.svg',
        'status' => 1,
    ],
    [
        'name' => 'Spain',
        'emoji' => '🇪🇸',
        'dial_code' => '+34',
        'image' => 'ES.svg',
        'status' => 1,
    ],
    [
        'name' => 'Ethiopia',
        'emoji' => '🇪🇹',
        'dial_code' => '+251',
        'image' => 'ET.svg',
        'status' => 1,
    ],
    [
        'name' => 'Finland',
        'emoji' => '🇫🇮',
        'dial_code' => '+358',
        'image' => 'FI.svg',
        'status' => 1,
    ],
    [
        'name' => 'Fiji',
        'emoji' => '🇫🇯',
        'dial_code' => '+679',
        'image' => 'FJ.svg',
        'status' => 1,
    ],
    [
        'name' => 'Falkland Islands',
        'emoji' => '🇫🇰',
        'dial_code' => '+500',
        'image' => 'FK.svg',
        'status' => 1,
    ],
    [
        'name' => 'Micronesia',
        'emoji' => '🇫🇲',
        'dial_code' => '+691',
        'image' => 'FM.svg',
        'status' => 1,
    ],
    [
        'name' => 'Faroe Islands',
        'emoji' => '🇫🇴',
        'dial_code' => '+298',
        'image' => 'FO.svg',
        'status' => 1,
    ],
    [
        'name' => 'France',
        'emoji' => '🇫🇷',
        'dial_code' => '+33',
        'image' => 'FR.svg',
        'status' => 1,
    ],
    [
        'name' => 'Gabon',
        'emoji' => '🇬🇦',
        'dial_code' => '+241',
        'image' => 'GA.svg',
        'status' => 1,
    ],
    [
        'name' => 'United Kingdom',
        'emoji' => '🇬🇧',
        'dial_code' => '+44',
        'image' => 'GB.svg',
        'status' => 1,
    ],
    [
        'name' => 'Grenada',
        'emoji' => '🇬🇩',
        'dial_code' => '+1473',
        'image' => 'GD.svg',
        'status' => 1,
    ],
    [
        'name' => 'Georgia',
        'emoji' => '🇬🇪',
        'dial_code' => '+995',
        'image' => 'GE.svg',
        'status' => 1,
    ],
    [
        'name' => 'French Guiana',
        'emoji' => '🇬🇫',
        'dial_code' => '+594',
        'image' => 'GF.svg',
        'status' => 1,
    ],
    [
        'name' => 'Guernsey',
        'emoji' => '🇬🇬',
        'dial_code' => '+44',
        'image' => 'GG.svg',
        'status' => 1,
    ],
    [
        'name' => 'Ghana',
        'emoji' => '🇬🇭',
        'dial_code' => '+233',
        'image' => 'GH.svg',
        'status' => 1,
    ],
    [
        'name' => 'Gibraltar',
        'emoji' => '🇬🇮',
        'dial_code' => '+350',
        'image' => 'GI.svg',
        'status' => 1,
    ],
    [
        'name' => 'Greenland',
        'emoji' => '🇬🇱',
        'dial_code' => '+299',
        'image' => 'GL.svg',
        'status' => 1,
    ],
    [
        'name' => 'Gambia',
        'emoji' => '🇬🇲',
        'dial_code' => '+220',
        'image' => 'GM.svg',
        'status' => 1,
    ],
    [
        'name' => 'Guinea',
        'emoji' => '🇬🇳',
        'dial_code' => '+224',
        'image' => 'GN.svg',
        'status' => 1,
    ],
    [
        'name' => 'Guadeloupe',
        'emoji' => '🇬🇵',
        'dial_code' => '+590',
        'image' => 'GP.svg',
        'status' => 1,
    ],
    [
        'name' => 'Equatorial Guinea',
        'emoji' => '🇬🇶',
        'dial_code' => '+240',
        'image' => 'GQ.svg',
        'status' => 1,
    ],
    [
        'name' => 'Greece',
        'emoji' => '🇬🇷',
        'dial_code' => '+30',
        'image' => 'GR.svg',
        'status' => 1,
    ],
    [
        'name' => 'South Georgia & South Sandwich Islands',
        'emoji' => '🇬🇸',
        'dial_code' => '+500',
        'image' => 'GS.svg',
        'status' => 1,
    ],
    [
        'name' => 'Guatemala',
        'emoji' => '🇬🇹',
        'dial_code' => '+502',
        'image' => 'GT.svg',
        'status' => 1,
    ],
    [
        'name' => 'Guam',
        'emoji' => '🇬🇺',
        'dial_code' => '+1671',
        'image' => 'GU.svg',
        'status' => 1,
    ],
    [
        'name' => 'Guinea-Bissau',
        'emoji' => '🇬🇼',
        'dial_code' => '+245',
        'image' => 'GW.svg',
        'status' => 1,
    ],
    [
        'name' => 'Guyana',
        'emoji' => '🇬🇾',
        'dial_code' => '+595',
        'image' => 'GY.svg',
        'status' => 1,
    ],
    [
        'name' => 'Hong Kong SAR China',
        'emoji' => '🇭🇰',
        'dial_code' => '+852',
        'image' => 'HK.svg',
        'status' => 1,
    ],
    [
        'name' => 'Honduras',
        'emoji' => '🇭🇳',
        'dial_code' => '+504',
        'image' => 'HN.svg',
        'status' => 1,
    ],
    [
        'name' => 'Croatia',
        'emoji' => '🇭🇷',
        'dial_code' => '+385',
        'image' => 'HR.svg',
        'status' => 1,
    ],
    [
        'name' => 'Haiti',
        'emoji' => '🇭🇹',
        'dial_code' => '+509',
        'image' => 'HT.svg',
        'status' => 1,
    ],
    [
        'name' => 'Hungary',
        'emoji' => '🇭🇺',
        'dial_code' => '+36',
        'image' => 'HU.svg',
        'status' => 1,
    ],
    [
        'name' => 'Indonesia',
        'emoji' => '🇮🇩',
        'dial_code' => '+62',
        'image' => 'ID.svg',
        'status' => 1,
    ],
    [
        'name' => 'Ireland',
        'emoji' => '🇮🇪',
        'dial_code' => '+353',
        'image' => 'IE.svg',
        'status' => 1,
    ],
    [
        'name' => 'Israel',
        'emoji' => '🇮🇱',
        'dial_code' => '+972',
        'image' => 'IL.svg',
        'status' => 1,
    ],
    [
        'name' => 'Isle of Man',
        'emoji' => '🇮🇲',
        'dial_code' => '+44',
        'image' => 'IM.svg',
        'status' => 1,
    ],
    [
        'name' => 'India',
        'emoji' => '🇮🇳',
        'dial_code' => '+91',
        'image' => 'IN.svg',
        'status' => 1,
    ],
    [
        'name' => 'British Indian Ocean Territory',
        'emoji' => '🇮🇴',
        'dial_code' => '+246',
        'image' => 'IO.svg',
        'status' => 1,
    ],
    [
        'name' => 'Iraq',
        'emoji' => '🇮🇶',
        'dial_code' => '+964',
        'image' => 'IQ.svg',
        'status' => 1,
    ],
    [
        'name' => 'Iran',
        'emoji' => '🇮🇷',
        'dial_code' => '+98',
        'image' => 'IR.svg',
        'status' => 1,
    ],
    [
        'name' => 'Iceland',
        'emoji' => '🇮🇸',
        'dial_code' => '+354',
        'image' => 'IS.svg',
        'status' => 1,
    ],
    [
        'name' => 'Italy',
        'emoji' => '🇮🇹',
        'dial_code' => '+39',
        'image' => 'IT.svg',
        'status' => 1,
    ],
    [
        'name' => 'Jersey',
        'emoji' => '🇯🇪',
        'dial_code' => '+44',
        'image' => 'JE.svg',
        'status' => 1,
    ],
    [
        'name' => 'Jamaica',
        'emoji' => '🇯🇲',
        'dial_code' => '+1876',
        'image' => 'JM.svg',
        'status' => 1,
    ],
    [
        'name' => 'Jordan',
        'emoji' => '🇯🇴',
        'dial_code' => '+962',
        'image' => 'JO.svg',
        'status' => 1,
    ],
    [
        'name' => 'Japan',
        'emoji' => '🇯🇵',
        'dial_code' => '+81',
        'image' => 'JP.svg',
        'status' => 1,
    ],
    [
        'name' => 'Kenya',
        'emoji' => '🇰🇪',
        'dial_code' => '+254',
        'image' => 'KE.svg',
        'status' => 1,
    ],
    [
        'name' => 'Kyrgyzstan',
        'emoji' => '🇰🇬',
        'dial_code' => '+996',
        'image' => 'KG.svg',
        'status' => 1,
    ],
    [
        'name' => 'Cambodia',
        'emoji' => '🇰🇭',
        'dial_code' => '+855',
        'image' => 'KH.svg',
        'status' => 1,
    ],
    [
        'name' => 'Kiribati',
        'emoji' => '🇰🇮',
        'dial_code' => '+686',
        'image' => 'KI.svg',
        'status' => 1,
    ],
    [
        'name' => 'Comoros',
        'emoji' => '🇰🇲',
        'dial_code' => '+269',
        'image' => 'KM.svg',
        'status' => 1,
    ],
    [
        'name' => 'St. Kitts & Nevis',
        'emoji' => '🇰🇳',
        'dial_code' => '+1869',
        'image' => 'KN.svg',
        'status' => 1,
    ],
    [
        'name' => 'North Korea',
        'emoji' => '🇰🇵',
        'dial_code' => '+850',
        'image' => 'KP.svg',
        'status' => 1,
    ],
    [
        'name' => 'South Korea',
        'emoji' => '🇰🇷',
        'dial_code' => '+82',
        'image' => 'KR.svg',
        'status' => 1,
    ],
    [
        'name' => 'Kuwait',
        'emoji' => '🇰🇼',
        'dial_code' => '+965',
        'image' => 'KW.svg',
        'status' => 1,
    ],
    [
        'name' => 'Cayman Islands',
        'emoji' => '🇰🇾',
        'dial_code' => '+ 345',
        'image' => 'KY.svg',
        'status' => 1,
    ],
    [
        'name' => 'Kazakhstan',
        'emoji' => '🇰🇿',
        'dial_code' => '+77',
        'image' => 'KZ.svg',
        'status' => 1,
    ],
    [
        'name' => 'Laos',
        'emoji' => '🇱🇦',
        'dial_code' => '+856',
        'image' => 'LA.svg',
        'status' => 1,
    ],
    [
        'name' => 'Lebanon',
        'emoji' => '🇱🇧',
        'dial_code' => '+961',
        'image' => 'LB.svg',
        'status' => 1,
    ],
    [
        'name' => 'St. Lucia',
        'emoji' => '🇱🇨',
        'dial_code' => '+1758',
        'image' => 'LC.svg',
        'status' => 1,
    ],
    [
        'name' => 'Liechtenstein',
        'emoji' => '🇱🇮',
        'dial_code' => '+423',
        'image' => 'LI.svg',
        'status' => 1,
    ],
    [
        'name' => 'Sri Lanka',
        'emoji' => '🇱🇰',
        'dial_code' => '+94',
        'image' => 'LK.svg',
        'status' => 1,
    ],
    [
        'name' => 'Liberia',
        'emoji' => '🇱🇷',
        'dial_code' => '+231',
        'image' => 'LR.svg',
        'status' => 1,
    ],
    [
        'name' => 'Lesotho',
        'emoji' => '🇱🇸',
        'dial_code' => '+266',
        'image' => 'LS.svg',
        'status' => 1,
    ],
    [
        'name' => 'Lithuania',
        'emoji' => '🇱🇹',
        'dial_code' => '+370',
        'image' => 'LT.svg',
        'status' => 1,
    ],
    [
        'name' => 'Luxembourg',
        'emoji' => '🇱🇺',
        'dial_code' => '+352',
        'image' => 'LU.svg',
        'status' => 1,
    ],
    [
        'name' => 'Latvia',
        'emoji' => '🇱🇻',
        'dial_code' => '+371',
        'image' => 'LV.svg',
        'status' => 1,
    ],
    [
        'name' => 'Libya',
        'emoji' => '🇱🇾',
        'dial_code' => '+218',
        'image' => 'LY.svg',
        'status' => 1,
    ],
    [
        'name' => 'Morocco',
        'emoji' => '🇲🇦',
        'dial_code' => '+212',
        'image' => 'MA.svg',
        'status' => 1,
    ],
    [
        'name' => 'Monaco',
        'emoji' => '🇲🇨',
        'dial_code' => '+377',
        'image' => 'MC.svg',
        'status' => 1,
    ],
    [
        'name' => 'Moldova',
        'emoji' => '🇲🇩',
        'dial_code' => '+373',
        'image' => 'MD.svg',
        'status' => 1,
    ],
    [
        'name' => 'Montenegro',
        'emoji' => '🇲🇪',
        'dial_code' => '+382',
        'image' => 'ME.svg',
        'status' => 1,
    ],
    [
        'name' => 'St. Martin',
        'emoji' => '🇲🇫',
        'dial_code' => '+590',
        'image' => 'MF.svg',
        'status' => 1,
    ],
    [
        'name' => 'Madagascar',
        'emoji' => '🇲🇬',
        'dial_code' => '+261',
        'image' => 'MG.svg',
        'status' => 1,
    ],
    [
        'name' => 'Marshall Islands',
        'emoji' => '🇲🇭',
        'dial_code' => '+692',
        'image' => 'MH.svg',
        'status' => 1,
    ],
    [
        'name' => 'North Macedonia',
        'emoji' => '🇲🇰',
        'dial_code' => '+389',
        'image' => 'MK.svg',
        'status' => 1,
    ],
    [
        'name' => 'Mali',
        'emoji' => '🇲🇱',
        'dial_code' => '+223',
        'image' => 'ML.svg',
        'status' => 1,
    ],
    [
        'name' => 'Myanmar (Burma)',
        'emoji' => '🇲🇲',
        'dial_code' => '+95',
        'image' => 'MM.svg',
        'status' => 1,
    ],
    [
        'name' => 'Mongolia',
        'emoji' => '🇲🇳',
        'dial_code' => '+976',
        'image' => 'MN.svg',
        'status' => 1,
    ],
    [
        'name' => 'Macao SAR China',
        'emoji' => '🇲🇴',
        'dial_code' => '+853',
        'image' => 'MO.svg',
        'status' => 1,
    ],
    [
        'name' => 'Northern Mariana Islands',
        'emoji' => '🇲🇵',
        'dial_code' => '+1670',
        'image' => 'MP.svg',
        'status' => 1,
    ],
    [
        'name' => 'Martinique',
        'emoji' => '🇲🇶',
        'dial_code' => '+596',
        'image' => 'MQ.svg',
        'status' => 1,
    ],
    [
        'name' => 'Mauritania',
        'emoji' => '🇲🇷',
        'dial_code' => '+222',
        'image' => 'MR.svg',
        'status' => 1,
    ],
    [
        'name' => 'Montserrat',
        'emoji' => '🇲🇸',
        'dial_code' => '+1664',
        'image' => 'MS.svg',
        'status' => 1,
    ],
    [
        'name' => 'Malta',
        'emoji' => '🇲🇹',
        'dial_code' => '+356',
        'image' => 'MT.svg',
        'status' => 1,
    ],
    [
        'name' => 'Mauritius',
        'emoji' => '🇲🇺',
        'dial_code' => '+230',
        'image' => 'MU.svg',
        'status' => 1,
    ],
    [
        'name' => 'Maldives',
        'emoji' => '🇲🇻',
        'dial_code' => '+960',
        'image' => 'MV.svg',
        'status' => 1,
    ],
    [
        'name' => 'Malawi',
        'emoji' => '🇲🇼',
        'dial_code' => '+265',
        'image' => 'MW.svg',
        'status' => 1,
    ],
    [
        'name' => 'Mexico',
        'emoji' => '🇲🇽',
        'dial_code' => '+52',
        'image' => 'MX.svg',
        'status' => 1,
    ],
    [
        'name' => 'Malaysia',
        'emoji' => '🇲🇾',
        'dial_code' => '+60',
        'image' => 'MY.svg',
        'status' => 1,
    ],
    [
        'name' => 'Mozambique',
        'emoji' => '🇲🇿',
        'dial_code' => '+258',
        'image' => 'MZ.svg',
        'status' => 1,
    ],
    [
        'name' => 'Namibia',
        'emoji' => '🇳🇦',
        'dial_code' => '+264',
        'image' => 'NA.svg',
        'status' => 1,
    ],
    [
        'name' => 'New Caledonia',
        'emoji' => '🇳🇨',
        'dial_code' => '+687',
        'image' => 'NC.svg',
        'status' => 1,
    ],
    [
        'name' => 'Niger',
        'emoji' => '🇳🇪',
        'dial_code' => '+227',
        'image' => 'NE.svg',
        'status' => 1,
    ],
    [
        'name' => 'Norfolk Island',
        'emoji' => '🇳🇫',
        'dial_code' => '+672',
        'image' => 'NF.svg',
        'status' => 1,
    ],
    [
        'name' => 'Nigeria',
        'emoji' => '🇳🇬',
        'dial_code' => '+234',
        'image' => 'NG.svg',
        'status' => 1,
    ],
    [
        'name' => 'Nicaragua',
        'emoji' => '🇳🇮',
        'dial_code' => '+505',
        'image' => 'NI.svg',
        'status' => 1,
    ],
    [
        'name' => 'Netherlands',
        'emoji' => '🇳🇱',
        'dial_code' => '+31',
        'image' => 'NL.svg',
        'status' => 1,
    ],
    [
        'name' => 'Norway',
        'emoji' => '🇳🇴',
        'dial_code' => '+47',
        'image' => 'NO.svg',
        'status' => 1,
    ],
    [
        'name' => 'Nepal',
        'emoji' => '🇳🇵',
        'dial_code' => '+977',
        'image' => 'NP.svg',
        'status' => 1,
    ],
    [
        'name' => 'Nauru',
        'emoji' => '🇳🇷',
        'dial_code' => '+674',
        'image' => 'NR.svg',
        'status' => 1,
    ],
    [
        'name' => 'Niue',
        'emoji' => '🇳🇺',
        'dial_code' => '+683',
        'image' => 'NU.svg',
        'status' => 1,
    ],
    [
        'name' => 'New Zealand',
        'emoji' => '🇳🇿',
        'dial_code' => '+64',
        'image' => 'NZ.svg',
        'status' => 1,
    ],
    [
        'name' => 'Oman',
        'emoji' => '🇴🇲',
        'dial_code' => '+968',
        'image' => 'OM.svg',
        'status' => 1,
    ],
    [
        'name' => 'Panama',
        'emoji' => '🇵🇦',
        'dial_code' => '+507',
        'image' => 'PA.svg',
        'status' => 1,
    ],
    [
        'name' => 'Peru',
        'emoji' => '🇵🇪',
        'dial_code' => '+51',
        'image' => 'PE.svg',
        'status' => 1,
    ],
    [
        'name' => 'French Polynesia',
        'emoji' => '🇵🇫',
        'dial_code' => '+689',
        'image' => 'PF.svg',
        'status' => 1,
    ],
    [
        'name' => 'Papua New Guinea',
        'emoji' => '🇵🇬',
        'dial_code' => '+675',
        'image' => 'PG.svg',
        'status' => 1,
    ],
    [
        'name' => 'Philippines',
        'emoji' => '🇵🇭',
        'dial_code' => '+63',
        'image' => 'PH.svg',
        'status' => 1,
    ],
    [
        'name' => 'Pakistan',
        'emoji' => '🇵🇰',
        'dial_code' => '+92',
        'image' => 'PK.svg',
        'status' => 1,
    ],
    [
        'name' => 'Poland',
        'emoji' => '🇵🇱',
        'dial_code' => '+48',
        'image' => 'PL.svg',
        'status' => 1,
    ],
    [
        'name' => 'St. Pierre & Miquelon',
        'emoji' => '🇵🇲',
        'dial_code' => '+508',
        'image' => 'PM.svg',
        'status' => 1,
    ],
    [
        'name' => 'Pitcairn Islands',
        'emoji' => '🇵🇳',
        'dial_code' => '+872',
        'image' => 'PN.svg',
        'status' => 1,
    ],
    [
        'name' => 'Puerto Rico',
        'emoji' => '🇵🇷',
        'dial_code' => '+1939',
        'image' => 'PR.svg',
        'status' => 1,
    ],
    [
        'name' => 'Palestinian Territories',
        'emoji' => '🇵🇸',
        'dial_code' => '+970',
        'image' => 'PS.svg',
        'status' => 1,
    ],
    [
        'name' => 'Portugal',
        'emoji' => '🇵🇹',
        'dial_code' => '+351',
        'image' => 'PT.svg',
        'status' => 1,
    ],
    [
        'name' => 'Palau',
        'emoji' => '🇵🇼',
        'dial_code' => '+680',
        'image' => 'PW.svg',
        'status' => 1,
    ],
    [
        'name' => 'Paraguay',
        'emoji' => '🇵🇾',
        'dial_code' => '+595',
        'image' => 'PY.svg',
        'status' => 1,
    ],
    [
        'name' => 'Qatar',
        'emoji' => '🇶🇦',
        'dial_code' => '+974',
        'image' => 'QA.svg',
        'status' => 1,
    ],
    [
        'name' => 'R',
        'emoji' => '🇷🇪',
        'dial_code' => '+262',
        'image' => 'RE.svg',
        'status' => 1,
    ],
    [
        'name' => 'Romania',
        'emoji' => '🇷🇴',
        'dial_code' => '+40',
        'image' => 'RO.svg',
        'status' => 1,
    ],
    [
        'name' => 'Serbia',
        'emoji' => '🇷🇸',
        'dial_code' => '+381',
        'image' => 'RS.svg',
        'status' => 1,
    ],
    [
        'name' => 'Russia',
        'emoji' => '🇷🇺',
        'dial_code' => '+7',
        'image' => 'RU.svg',
        'status' => 1,
    ],
    [
        'name' => 'Rwanda',
        'emoji' => '🇷🇼',
        'dial_code' => '+250',
        'image' => 'RW.svg',
        'status' => 1,
    ],
    [
        'name' => 'Saudi Arabia',
        'emoji' => '🇸🇦',
        'dial_code' => '+966',
        'image' => 'SA.svg',
        'status' => 1,
    ],
    [
        'name' => 'Solomon Islands',
        'emoji' => '🇸🇧',
        'dial_code' => '+677',
        'image' => 'SB.svg',
        'status' => 1,
    ],
    [
        'name' => 'Seychelles',
        'emoji' => '🇸🇨',
        'dial_code' => '+248',
        'image' => 'SC.svg',
        'status' => 1,
    ],
    [
        'name' => 'Sudan',
        'emoji' => '🇸🇩',
        'dial_code' => '+249',
        'image' => 'SD.svg',
        'status' => 1,
    ],
    [
        'name' => 'Sweden',
        'emoji' => '🇸🇪',
        'dial_code' => '+46',
        'image' => 'SE.svg',
        'status' => 1,
    ],
    [
        'name' => 'Singapore',
        'emoji' => '🇸🇬',
        'dial_code' => '+65',
        'image' => 'SG.svg',
        'status' => 1,
    ],
    [
        'name' => 'St. Helena',
        'emoji' => '🇸🇭',
        'dial_code' => '+290',
        'image' => 'SH.svg',
        'status' => 1,
    ],
    [
        'name' => 'Slovenia',
        'emoji' => '🇸🇮',
        'dial_code' => '+386',
        'image' => 'SI.svg',
        'status' => 1,
    ],
    [
        'name' => 'Svalbard & Jan Mayen',
        'emoji' => '🇸🇯',
        'dial_code' => '+47',
        'image' => 'SJ.svg',
        'status' => 1,
    ],
    [
        'name' => 'Slovakia',
        'emoji' => '🇸🇰',
        'dial_code' => '+421',
        'image' => 'SK.svg',
        'status' => 1,
    ],
    [
        'name' => 'Sierra Leone',
        'emoji' => '🇸🇱',
        'dial_code' => '+232',
        'image' => 'SL.svg',
        'status' => 1,
    ],
    [
        'name' => 'San Marino',
        'emoji' => '🇸🇲',
        'dial_code' => '+378',
        'image' => 'SM.svg',
        'status' => 1,
    ],
    [
        'name' => 'Senegal',
        'emoji' => '🇸🇳',
        'dial_code' => '+221',
        'image' => 'SN.svg',
        'status' => 1,
    ],
    [
        'name' => 'Somalia',
        'emoji' => '🇸🇴',
        'dial_code' => '+252',
        'image' => 'SO.svg',
        'status' => 1,
    ],
    [
        'name' => 'Suriname',
        'emoji' => '🇸🇷',
        'dial_code' => '+597',
        'image' => 'SR.svg',
        'status' => 1,
    ],
    [
        'name' => 'South Sudan',
        'emoji' => '🇸🇸',
        'dial_code' => '+211',
        'image' => 'SS.svg',
        'status' => 1,
    ],
    [
        'name' => 'S',
        'emoji' => '🇸🇹',
        'dial_code' => '+239',
        'image' => 'ST.svg',
        'status' => 1,
    ],
    [
        'name' => 'El Salvador',
        'emoji' => '🇸🇻',
        'dial_code' => '+503',
        'image' => 'SV.svg',
        'status' => 1,
    ],
    [
        'name' => 'Syria',
        'emoji' => '🇸🇾',
        'dial_code' => '+963',
        'image' => 'SY.svg',
        'status' => 1,
    ],
    [
        'name' => 'Eswatini',
        'emoji' => '🇸🇿',
        'dial_code' => '+268',
        'image' => 'SZ.svg',
        'status' => 1,
    ],
    [
        'name' => 'Turks & Caicos Islands',
        'emoji' => '🇹🇨',
        'dial_code' => '+1649',
        'image' => 'TC.svg',
        'status' => 1,
    ],
    [
        'name' => 'Chad',
        'emoji' => '🇹🇩',
        'dial_code' => '+235',
        'image' => 'TD.svg',
        'status' => 1,
    ],
    [
        'name' => 'Togo',
        'emoji' => '🇹🇬',
        'dial_code' => '+228',
        'image' => 'TG.svg',
        'status' => 1,
    ],
    [
        'name' => 'Thailand',
        'emoji' => '🇹🇭',
        'dial_code' => '+66',
        'image' => 'TH.svg',
        'status' => 1,
    ],
    [
        'name' => 'Tajikistan',
        'emoji' => '🇹🇯',
        'dial_code' => '+992',
        'image' => 'TJ.svg',
        'status' => 1,
    ],
    [
        'name' => 'Tokelau',
        'emoji' => '🇹🇰',
        'dial_code' => '+690',
        'image' => 'TK.svg',
        'status' => 1,
    ],
    [
        'name' => 'Timor-Leste',
        'emoji' => '🇹🇱',
        'dial_code' => '+670',
        'image' => 'TL.svg',
        'status' => 1,
    ],
    [
        'name' => 'Turkmenistan',
        'emoji' => '🇹🇲',
        'dial_code' => '+993',
        'image' => 'TM.svg',
        'status' => 1,
    ],
    [
        'name' => 'Tunisia',
        'emoji' => '🇹🇳',
        'dial_code' => '+216',
        'image' => 'TN.svg',
        'status' => 1,
    ],
    [
        'name' => 'Tonga',
        'emoji' => '🇹🇴',
        'dial_code' => '+676',
        'image' => 'TO.svg',
        'status' => 1,
    ],
    [
        'name' => 'Turkey',
        'emoji' => '🇹🇷',
        'dial_code' => '+90',
        'image' => 'TR.svg',
        'status' => 1,
    ],
    [
        'name' => 'Trinidad & Tobago',
        'emoji' => '🇹🇹',
        'dial_code' => '+1868',
        'image' => 'TT.svg',
        'status' => 1,
    ],
    [
        'name' => 'Tuvalu',
        'emoji' => '🇹🇻',
        'dial_code' => '+688',
        'image' => 'TV.svg',
        'status' => 1,
    ],
    [
        'name' => 'Taiwan',
        'emoji' => '🇹🇼',
        'dial_code' => '+886',
        'image' => 'TW.svg',
        'status' => 1,
    ],
    [
        'name' => 'Tanzania',
        'emoji' => '🇹🇿',
        'dial_code' => '+255',
        'image' => 'TZ.svg',
        'status' => 1,
    ],
    [
        'name' => 'Ukraine',
        'emoji' => '🇺🇦',
        'dial_code' => '+380',
        'image' => 'UA.svg',
        'status' => 1,
    ],
    [
        'name' => 'Uganda',
        'emoji' => '🇺🇬',
        'dial_code' => '+256',
        'image' => 'UG.svg',
        'status' => 1,
    ],
    [
        'name' => 'United States',
        'emoji' => '🇺🇸',
        'dial_code' => '+1',
        'image' => 'US.svg',
        'status' => 1,
    ],
    [
        'name' => 'Uruguay',
        'emoji' => '🇺🇾',
        'dial_code' => '+598',
        'image' => 'UY.svg',
        'status' => 1,
    ],
    [
        'name' => 'Uzbekistan',
        'emoji' => '🇺🇿',
        'dial_code' => '+998',
        'image' => 'UZ.svg',
        'status' => 1,
    ],
    [
        'name' => 'Vatican City',
        'emoji' => '🇻🇦',
        'dial_code' => '+379',
        'image' => 'VA.svg',
        'status' => 1,
    ],
    [
        'name' => 'St. Vincent & Grenadines',
        'emoji' => '🇻🇨',
        'dial_code' => '+1784',
        'image' => 'VC.svg',
        'status' => 1,
    ],
    [
        'name' => 'Venezuela',
        'emoji' => '🇻🇪',
        'dial_code' => '+58',
        'image' => 'VE.svg',
        'status' => 1,
    ],
    [
        'name' => 'British Virgin Islands',
        'emoji' => '🇻🇬',
        'dial_code' => '+1284',
        'image' => 'VG.svg',
        'status' => 1,
    ],
    [
        'name' => 'U.S. Virgin Islands',
        'emoji' => '🇻🇮',
        'dial_code' => '+1340',
        'image' => 'VI.svg',
        'status' => 1,
    ],
    [
        'name' => 'Vietnam',
        'emoji' => '🇻🇳',
        'dial_code' => '+84',
        'image' => 'VN.svg',
        'status' => 1,
    ],
    [
        'name' => 'Vanuatu',
        'emoji' => '🇻🇺',
        'dial_code' => '+678',
        'image' => 'VU.svg',
        'status' => 1,
    ],
    [
        'name' => 'Wallis & Futuna',
        'emoji' => '🇼🇫',
        'dial_code' => '+681',
        'image' => 'WF.svg',
        'status' => 1,
    ],
    [
        'name' => 'Samoa',
        'emoji' => '🇼🇸',
        'dial_code' => '+685',
        'image' => 'WS.svg',
        'status' => 1,
    ],
    [
        'name' => 'Yemen',
        'emoji' => '🇾🇪',
        'dial_code' => '+967',
        'image' => 'YE.svg',
        'status' => 1,
    ],
    [
        'name' => 'Mayotte',
        'emoji' => '🇾🇹',
        'dial_code' => '+262',
        'image' => 'YT.svg',
        'status' => 1,
    ],
    [
        'name' => 'South Africa',
        'emoji' => '🇿🇦',
        'dial_code' => '+27',
        'image' => 'ZA.svg',
        'status' => 1,
    ],
    [
        'name' => 'Zambia',
        'emoji' => '🇿🇲',
        'dial_code' => '+260',
        'image' => 'ZM.svg',
        'status' => 1,
    ],
    [
        'name' => 'Zimbabwe',
        'emoji' => '🇿🇼',
        'dial_code' => '+263',
        'image' => 'ZW.svg',
        'status' => 1,
    ],

];
return $data;